export enum TransactionStatus {
  RECEIVED = 'RECEIVED',

  PENDING = 'PENDING',

  AWAITING_CALLBACK = 'AWAITING_CALLBACK',

  SUCCESS = 'SUCCESS',

  FAILED = 'FAILED',

  CANCELLED = 'CANCELLED',

  REFUNDED = 'REFUNDED',

  QUERY_SUCCESS = 'QUERY_SUCCESS',
}
